export const countries = {
    "India": "Delhi",
    "United States": "Washington",
    "China": "Beijing",
    "Japan": "Tokyo",
    "United Kingdom": "London",
    "Germany": "Berlin",
    "France": "Paris",
    "Canada": "Ottawa",
    "Australia": "Canberra",
    "Russia": "Moscow",
    "Brazil": "Brasília",
    "Italy": "Rome",
    "South Korea": "Seoul",
    "Spain": "Madrid",
    "Mexico": "MexicoCity",
    "Indonesia": "Jakarta",
    "Turkey": "Ankara",
    "Saudi Arabia": "Riyadh",
    "United Arab Emirates": "AbuDhabi",
    "Singapore": "Singapore",
    "South Africa": "Pretoria",
    "Pakistan": "Islamabad",
    "Bangladesh": "Dhaka",
    "Nepal": "Kathmandu",
    "Sri Lanka": "Colombo",
    "Thailand": "Bangkok",
    "Malaysia": "KualaLumpur",
    "Vietnam": "Hanoi",
    "Philippines": "Manila",
    "New Zealand": "Wellington",
    "Netherlands": "Amsterdam",
    "Switzerland": "Bern",
    "Sweden": "Stockholm",
    "Norway": "Oslo",
    "Denmark": "Copenhagen",
    "Finland": "Helsinki",
    "Poland": "Warsaw",
    "Ukraine": "Kyiv",
    "Argentina": "BuenosAires",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "Peru": "Lima",
    "Egypt": "Cairo",
    "Nigeria": "Abuja",
    "Kenya": "Nairobi",
    "Morocco": "Rabat",
    "Israel": "Jerusalem",
    "Qatar": "Doha",
    "Kuwait": "KuwaitCity",
    "Oman": "Muscat",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Afghanistan": "Kabul",
    "Bhutan": "Thimphu",
    "Myanmar": "Naypyidaw",
    "Cambodia": "PhnomPenh",
    "Laos": "Vientiane",
    "Mongolia": "Ulaanbaatar",
    "Kazakhstan": "Astana",
    "Uzbekistan": "Tashkent",
    "Tajikistan": "Dushanbe",
    "Kyrgyzstan": "Bishkek",
    "Turkmenistan": "Ashgabat"
};

export const latitudes = {

    Delhi: 28.61,
    Washington: 38.89,
    Beijing: 39.90,
    Tokyo: 35.68,
    London: 51.50,
    Berlin: 52.52,
    Paris: 48.85,
    Ottawa: 45.42,
    Canberra: -35.28,
    Moscow: 55.75,
    Brasília: -15.79,
    Rome: 41.90,
    Seoul: 37.56,
    Madrid: 40.41,
    MexicoCity: 19.43,
    Jakarta: -6.20,
    Ankara: 39.93,
    Riyadh: 24.71,
    AbuDhabi: 24.45,
    Singapore: 1.29,
    Pretoria: -25.74,
    Islamabad: 33.69,
    Dhaka: 23.81,
    Kathmandu: 27.71,
    Colombo: 6.93,
    Bangkok: 13.75,
    KualaLumpur: 3.14,
    Hanoi: 21.03,
    Manila: 14.59,
    Wellington: -41.28

};

export const longitudes = {

    Delhi: 77.21,
    Washington: -77.03,
    Beijing: 116.40,
    Tokyo: 139.69,
    London: -0.12,
    Berlin: 13.40,
    Paris: 2.35,
    Ottawa: -75.69,
    Canberra: 149.13,
    Moscow: 37.61,
    Brasília: -47.88,
    Rome: 12.49,
    Seoul: 126.97,
    Madrid: -3.70,
    MexicoCity: -99.13,
    Jakarta: 106.81,
    Ankara: 32.85,
    Riyadh: 46.67,
    AbuDhabi: 54.37,
    Singapore: 103.85,
    Pretoria: 28.18,
    Islamabad: 73.06,
    Dhaka: 90.41,
    Kathmandu: 85.32,
    Colombo: 79.86,
    Bangkok: 100.50,
    KualaLumpur: 101.69,
    Hanoi: 105.85,
    Manila: 120.98,
    Wellington: 174.77

};